server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false #配置此属性是修改html页面时不用重启项目，按shift+ctrl+f9，再刷新前台访问的页面
  rabbitmq:
    host: 192.168.200.128
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka