server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    refresh:
      refreshable: none  #不加入会造成循环依赖?
#注册中心
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
#网关
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** #商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** #用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
    order-service: /order/** # 订单微服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true  #携带请求本身的header头信息
  sensitive-headers:  #配置禁止使用的头信息，这里设置为null，否则set-cookie无效
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 7000

#分布式系统的延迟和容错库，熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#是一个基于HTTP和TCP的客户端负载均衡工具
ribbon:
  ConnectTimeout: 5000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 5000 #请求处理的超时时间
  #关闭重试,避免重复提交请求
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

leyou:
  jwt:
    pubKeyPath:  C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    # filter白名单
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item


