server:  #短信微服务
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.200.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.200.128
ly:
  sms:
    accessKeyId: LTAI4G4fvPM5RgMRLii8mCTS
    accessKeySecret: VP1SNwvgJrd3SRzUuwDGVQ7b6R6lcj
    signName: 乐优商城
    verifyCodeTemplate: SMS_205121189
