server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false   # 是否向eureka注册自身服务
    fetch-registry: false  #是否检索服务
  server:
    peer-node-read-timeout-ms: 500
